services:
  - type: web
    plan: free
    name: 456cafe-api
    runtime: node
    region: oregon
    rootDir: backend
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: node dist-new/src/main.js
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: NODE_ENV
        value: production
